// Человекочитаемые названия типов сущностей
export const ENTITY_TYPE_LABELS: Record<string, string> = {
  opt: "Опт",
  aircraft_refueling: "Заправка ВС",
  aircraft_refueling_abroad: "Заправка ВС (загран.)",
  movement: "Перемещение",
  exchange: "Обмен",
  warehouses: "Склад",
  prices: "Прайс",
  suppliers: "Поставщик",
  customers: "Покупатель",
  bases: "База",
  logistics_carriers: "Перевозчик",
  logistics_delivery_locations: "Место доставки",
  logistics_vehicles: "Транспортное средство",
  logistics_trailers: "Прицеп",
  logistics_drivers: "Водитель",
  delivery_cost: "Тариф доставки",
  cashflow_transactions: "Движение ДС",
  payment_calendar: "Платёжный календарь",
  price_calculations: "Расчёт цен",
  users: "Пользователь",
  roles: "Роль",
  exchange_rates: "Курс валюты",
  storage_cards: "Карта хранения",
  equipment: "Оборудование",
  equipment_movement: "Перемещение оборудования",
  transportation: "Перевозка",
  railway_stations: "Ж/д станция",
  railway_tariffs: "Ж/д тариф",
  exchange_deals: "Обменная сделка",
  exchange_advance_cards: "Авансовая карта",
  plan_entries: "Плановая запись",
  free_volume_allocations: "Свободный объём",
  logistics_transport_units: "Транспортная единица",
  logistics_plan_routes: "Маршрут",
  planning_resource: "Ресурс планирования",
};

// Поля-маппинг для различных типов сущностей
export const FIELD_LABELS: Record<string, Record<string, string>> = {
  opt: {
    basis: "Базис",
    buyerId: "Покупатель",
    supplierId: "Поставщик",
    carrierId: "Перевозчик",
    deliveryLocationId: "Место доставки",
    warehouseId: "Склад",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    purchasePrice: "Цена покупки",
    salePrice: "Цена продажи",
    purchaseAmount: "Сумма покупки",
    saleAmount: "Сумма продажи",
    profit: "Прибыль",
    deliveryCost: "Стоимость доставки",
    deliveryTariff: "Тариф доставки",
    notes: "Примечания",
    isApproxVolume: "Примерный объём",
    density: "Плотность",
    dealDate: "Дата сделки",
    contractNumber: "Номер договора",
    salePriceIndex: "Индекс цены продажи",
    purchasePriceIndex: "Индекс цены покупки",
    purchasePriceModified: "Цена покупки изменена",
  },
  aircraft_refueling: {
    refuelingDate: "Дата заправки",
    aircraftNumber: "Номер ВС",
    buyerId: "Покупатель",
    supplierId: "Поставщик",
    warehouseId: "Склад",
    productType: "Тип продукта",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    density: "Плотность",
    purchasePrice: "Цена покупки",
    salePrice: "Цена продажи",
    purchaseAmount: "Сумма покупки",
    saleAmount: "Сумма продажи",
    profit: "Прибыль",
    notes: "Примечания",
    contractNumber: "Номер договора",
    salePriceIndex: "Индекс цены продажи",
    purchasePriceIndex: "Индекс цены покупки",
    agentFeeRate: "Агентский сбор (%)",
    otherServiceFeeName: "Доп. услуга: название",
    otherServiceFeeType: "Доп. услуга: тип",
    otherServiceFeeQty: "Доп. услуга: кол-во",
    agentFeeEnabled: "Агентский сбор включён",
    otherServiceFeeEnabled: "Доп. услуга включена",
  },
  aircraft_refueling_abroad: {
    refuelingDate: "Дата заправки",
    aircraftNumber: "Номер ВС",
    buyerId: "Покупатель",
    supplierId: "Поставщик",
    warehouseId: "Склад",
    productType: "Тип продукта",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    density: "Плотность",
    purchasePrice: "Цена покупки",
    salePrice: "Цена продажи",
    purchaseAmount: "Сумма покупки",
    saleAmount: "Сумма продажи",
    profit: "Прибыль",
    currency: "Валюта",
    exchangeRate: "Курс",
    notes: "Примечания",
    contractNumber: "Номер договора",
  },
  exchange: {
    exchangeDate: "Дата обмена",
    supplierId: "Поставщик",
    warehouseId: "Склад",
    productType: "Тип продукта",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    density: "Плотность",
    notes: "Примечания",
  },
  movement: {
    movementDate: "Дата перемещения",
    sourceWarehouseId: "Склад отправления",
    destinationWarehouseId: "Склад назначения",
    carrierId: "Перевозчик",
    productType: "Тип продукта",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    density: "Плотность",
    deliveryCost: "Стоимость доставки",
    notes: "Примечания",
  },
  warehouses: {
    name: "Название",
    location: "Местоположение",
    capacity: "Вместимость",
    currentStock: "Текущий остаток",
    isActive: "Активен",
    type: "Тип",
    description: "Описание",
  },
  prices: {
    supplierId: "Поставщик",
    productType: "Тип продукта",
    price: "Цена",
    startDate: "Дата начала",
    endDate: "Дата окончания",
    notes: "Примечания",
  },
  suppliers: {
    name: "Название",
    inn: "ИНН",
    contractNumber: "Номер договора",
    contactPerson: "Контактное лицо",
    phone: "Телефон",
    email: "Email",
    description: "Описание",
    isActive: "Активен",
    isWarehouse: "Является складом",
  },
  customers: {
    name: "Название",
    inn: "ИНН",
    contractNumber: "Номер договора",
    contactPerson: "Контактное лицо",
    phone: "Телефон",
    email: "Email",
    description: "Описание",
    isActive: "Активен",
  },
  users: {
    email: "Email",
    firstName: "Имя",
    lastName: "Фамилия",
    roleId: "Роль",
    isActive: "Активен",
    lastLoginAt: "Последний вход",
  },
  roles: {
    name: "Название",
    description: "Описание",
    permissions: "Права доступа",
    isSystem: "Системная роль",
    isDefault: "По умолчанию",
  },
  bases: {
    name: "Название",
    location: "Местоположение",
    type: "Тип",
    isActive: "Активен",
    description: "Описание",
    code: "Код",
  },
  logistics_carriers: {
    name: "Название",
    inn: "ИНН",
    contactPerson: "Контактное лицо",
    phone: "Телефон",
    email: "Email",
    description: "Описание",
    isActive: "Активен",
  },
  logistics_delivery_locations: {
    name: "Название",
    address: "Адрес",
    city: "Город",
    isActive: "Активен",
    notes: "Примечания",
    code: "Код",
  },
  logistics_vehicles: {
    licensePlate: "Гос. номер",
    model: "Модель",
    brand: "Марка",
    year: "Год выпуска",
    capacity: "Грузоподъёмность",
    carrierId: "Перевозчик",
    isActive: "Активен",
    notes: "Примечания",
    type: "Тип ТС",
  },
  logistics_trailers: {
    licensePlate: "Гос. номер",
    model: "Модель",
    capacity: "Объём (л)",
    carrierId: "Перевозчик",
    isActive: "Активен",
    notes: "Примечания",
    type: "Тип прицепа",
  },
  logistics_drivers: {
    firstName: "Имя",
    lastName: "Фамилия",
    phone: "Телефон",
    licenseNumber: "Номер прав",
    carrierId: "Перевозчик",
    isActive: "Активен",
    notes: "Примечания",
    schedule: "График работы",
  },
  delivery_cost: {
    name: "Название",
    carrierId: "Перевозчик",
    fromLocationId: "Откуда",
    toLocationId: "Куда",
    costPerKg: "Цена за кг",
    costPerLiter: "Цена за л",
    minCost: "Мин. стоимость",
    isActive: "Активен",
    notes: "Примечания",
    days: "Сутки",
    priority: "Приоритет",
    vehicleType: "Тип ТС",
  },
  cashflow_transactions: {
    transactionDate: "Дата транзакции",
    category: "Категория",
    subcategory: "Подкатегория",
    amount: "Сумма",
    currency: "Валюта",
    description: "Описание",
    counterparty: "Контрагент",
    paymentMethod: "Способ оплаты",
    isPlanned: "Планируемый",
    notes: "Примечания",
  },
  payment_calendar: {
    dueDate: "Срок оплаты",
    title: "Название",
    description: "Описание",
    amount: "Сумма",
    currency: "Валюта",
    category: "Категория",
    counterparty: "Контрагент",
    status: "Статус",
    paidDate: "Дата оплаты",
    paidAmount: "Оплаченная сумма",
    isRecurring: "Повторяющийся",
    recurringPeriod: "Период повторения",
    notes: "Примечания",
  },
  price_calculations: {
    name: "Название",
    productType: "Тип продукта",
    baseCost: "Базовая стоимость",
    additionalCosts: "Дополнительные расходы",
    totalCost: "Общая себестоимость",
    sellingPrice: "Цена продажи",
    margin: "Маржа",
    marginPercentage: "Маржа %",
    isTemplate: "Шаблон",
    notes: "Примечания",
  },
  equipment: {
    name: "Название",
    type: "Тип",
    serialNumber: "Серийный номер",
    warehouseId: "Склад",
    status: "Статус",
    notes: "Примечания",
    quantity: "Количество",
    unit: "Ед. измерения",
  },
  equipment_movement: {
    equipmentId: "Оборудование",
    fromWarehouseId: "Склад отправления",
    toWarehouseId: "Склад назначения",
    movementDate: "Дата перемещения",
    quantity: "Количество",
    notes: "Примечания",
  },
  transportation: {
    date: "Дата",
    carrierId: "Перевозчик",
    vehicleId: "ТС",
    driverId: "Водитель",
    fromLocationId: "Откуда",
    toLocationId: "Куда",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    cost: "Стоимость",
    notes: "Примечания",
    status: "Статус",
  },
  railway_stations: {
    name: "Название",
    code: "Код станции",
    city: "Город",
    isActive: "Активна",
    region: "Регион",
  },
  railway_tariffs: {
    fromStationId: "Станция отправления",
    toStationId: "Станция назначения",
    carrierId: "Перевозчик",
    costPerTon: "Цена за тонну",
    minCost: "Мин. стоимость",
    isActive: "Активен",
    validFrom: "Действует с",
    validTo: "Действует до",
    notes: "Примечания",
  },
  exchange_deals: {
    dealDate: "Дата сделки",
    partnerId: "Партнёр",
    productType: "Тип продукта",
    quantityKg: "Количество (кг)",
    pricePerKg: "Цена за кг",
    totalAmount: "Сумма",
    currency: "Валюта",
    notes: "Примечания",
    status: "Статус",
  },
  exchange_advance_cards: {
    date: "Дата",
    partnerId: "Партнёр",
    amount: "Сумма",
    currency: "Валюта",
    purpose: "Назначение",
    status: "Статус",
    notes: "Примечания",
  },
  exchange_rates: {
    currency: "Валюта",
    rate: "Курс",
    date: "Дата",
    source: "Источник",
  },
  storage_cards: {
    warehouseId: "Склад",
    productType: "Тип продукта",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    date: "Дата",
    notes: "Примечания",
    density: "Плотность",
  },
  plan_entries: {
    planDate: "Дата плана",
    scenarioId: "Сценарий",
    basisId: "Базис",
    warehouseId: "Склад",
    productType: "Тип продукта",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    notes: "Примечания",
    supplierId: "Поставщик",
    buyerId: "Покупатель",
  },
  free_volume_allocations: {
    allocDate: "Дата",
    warehouseId: "Склад",
    productType: "Тип продукта",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    basisId: "Базис",
    notes: "Примечания",
  },
  logistics_transport_units: {
    vehicleId: "ТС",
    trailerId: "Прицеп",
    driverId: "Водитель",
    scenarioId: "Сценарий",
    routeDate: "Дата маршрута",
    status: "Статус",
    notes: "Примечания",
    departureTime: "Время выезда",
  },
  logistics_plan_routes: {
    transportUnitId: "Транспортная единица",
    deliveryLocationId: "Место доставки",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    orderIndex: "Порядок",
    plannedArrival: "Плановое прибытие",
    notes: "Примечания",
    carrierId: "Перевозчик",
  },
  planning_resource: {
    date: "Дата",
    warehouseId: "Склад",
    basisId: "Базис",
    productType: "Тип продукта",
    quantityKg: "Количество (кг)",
    quantityLiters: "Количество (л)",
    notes: "Примечания",
  },
};

/**
 * Получить читаемое название поля для конкретного типа сущности
 */
export function getFieldLabel(entityType: string, fieldName: string): string {
  const entityLabels = FIELD_LABELS[entityType];
  if (entityLabels && entityLabels[fieldName]) {
    return entityLabels[fieldName];
  }
  // Fallback: camelCase → readable
  return fieldName
    .replace(/([A-Z])/g, ' $1')
    .replace(/_/g, ' ')
    .trim()
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

/**
 * Проверить, является ли поле техническим (скрытым от пользователя)
 */
export const TECHNICAL_FIELDS = new Set([
  'id',
  'createdAt',
  'updatedAt',
  'deletedAt',
  'createdById',
  'updatedById',
  'deletedById',
  'transactionId',
  'ipAddress',
  'userAgent',
  'rolledBackAt',
  'rolledBackById',
  'entityDeleted',
  'deletedBy',
  'version',
  'basisId',      // internal scenario reference shown as scenarioId
]);

/**
 * Проверить, нужно ли показывать поле пользователю
 */
export function isFieldVisible(entityType: string, fieldName: string): boolean {
  if (TECHNICAL_FIELDS.has(fieldName)) return false;
  // Skip unknown *Id fields (FK UUIDs without label mapping)
  if (fieldName.endsWith('Id') || fieldName.endsWith('_id')) {
    const entityLabels = FIELD_LABELS[entityType];
    if (!entityLabels || !entityLabels[fieldName]) return false;
  }
  return true;
}
