
import type { ModuleExportConfig } from "../entities/export-config";

export const optExportConfig: ModuleExportConfig = {
  moduleName: "opt",
  tableName: "opt",
  displayName: "Оптовые продажи",
  columns: [
    { key: "dealDate",              label: "Дата",              type: "date",   exportable: true },
    { key: "productType",           label: "Продукт",           type: "string", exportable: true },
    { key: "supplier.name",         label: "Поставщик",         type: "string", exportable: true },
    { key: "buyer.name",            label: "Покупатель",        type: "string", exportable: true },
    { key: "quantityKg",            label: "КГ",                type: "number", exportable: true },
    { key: "purchasePrice",         label: "Цена покупки",      type: "number", exportable: true },
    { key: "purchaseAmount",        label: "Покупка (₽)",       type: "number", exportable: true },
    { key: "salePrice",             label: "Цена продажи",      type: "number", exportable: true },
    { key: "saleAmount",            label: "Продажа (₽)",       type: "number", exportable: true },
    { key: "deliveryLocation.name", label: "Место доставки",    type: "string", exportable: true },
    { key: "carrier.name",          label: "Перевозчик",        type: "string", exportable: true },
    { key: "deliveryCost",          label: "Доставка (₽)",      type: "number", exportable: true },
    { key: "profit",                label: "Прибыль (₽)",       type: "number", exportable: true },
    { key: "notes",                 label: "Примечания",        type: "string", exportable: true },
  ],
  defaultColumns: ["dealDate","productType","supplier.name","buyer.name","quantityKg","purchasePrice","salePrice","saleAmount","profit"],
  relations: ["supplier","buyer","deliveryLocation","carrier"],
};

export const refuelingExportConfig: ModuleExportConfig = {
  moduleName: "refueling",
  tableName: "aircraft_refueling",
  displayName: "Заправка ВС",
  columns: [
    { key: "refuelingDate",  label: "Дата",          type: "date",   exportable: true },
    { key: "productType",    label: "Продукт",       type: "string", exportable: true },
    { key: "aircraftNumber", label: "Борт",          type: "string", exportable: true },
    { key: "supplier.name",  label: "Поставщик",     type: "string", exportable: true },
    { key: "basis.name",     label: "Базис",         type: "string", exportable: true },
    { key: "buyer.name",     label: "Покупатель",    type: "string", exportable: true },
    { key: "quantityLiters", label: "Лит.",          type: "number", exportable: true },
    { key: "density",        label: "Плотность",     type: "number", exportable: true },
    { key: "quantityKg",     label: "КГ",            type: "number", exportable: true },
    { key: "purchasePrice",  label: "Цена покупки",  type: "number", exportable: true },
    { key: "salePrice",      label: "Цена продажи",  type: "number", exportable: true },
    { key: "saleAmount",     label: "Продажа (₽)",   type: "number", exportable: true },
    { key: "profit",         label: "Прибыль (₽)",   type: "number", exportable: true },
    { key: "notes",          label: "Примечания",    type: "string", exportable: true },
  ],
  defaultColumns: ["refuelingDate","productType","aircraftNumber","supplier.name","basis.name","buyer.name","quantityKg","salePrice","saleAmount","profit"],
  relations: ["supplier","buyer","basis"],
};

export const movementExportConfig: ModuleExportConfig = {
  moduleName: "movement",
  tableName: "movement",
  displayName: "Перемещения",
  columns: [
    { key: "movementDate",          label: "Дата",           type: "date",   exportable: true },
    { key: "movementType",          label: "Тип",            type: "string", exportable: true },
    { key: "productType",           label: "Продукт",        type: "string", exportable: true },
    { key: "fromName",              label: "Откуда",         type: "string", exportable: true },
    { key: "toName",                label: "Куда",           type: "string", exportable: true },
    { key: "quantityKg",            label: "КГ",             type: "number", exportable: true },
    { key: "purchasePrice",         label: "Цена (₽/кг)",    type: "number", exportable: true },
    { key: "_purchaseAmount",       label: "Сумма (₽)",      type: "number", exportable: true },
    { key: "carrierName",           label: "Перевозчик",     type: "string", exportable: true },
    { key: "deliveryCost",          label: "Доставка (₽)",   type: "number", exportable: true },
    { key: "storageCost",           label: "Хранение (₽)",   type: "number", exportable: true },
    { key: "warehouseServicesCost", label: "Услуги (₽)",     type: "number", exportable: true },
    { key: "costPerKg",             label: "Себест. (₽/кг)", type: "number", exportable: true },
    { key: "notes",                 label: "Примечания",     type: "string", exportable: true },
  ],
  defaultColumns: ["movementDate","movementType","productType","fromName","toName","quantityKg","purchasePrice","deliveryCost","costPerKg"],
  relations: [],
};

export const exchangeDealsExportConfig: ModuleExportConfig = {
  moduleName: "exchange-deals",
  tableName: "exchange_deals",
  displayName: "Сделки Биржи",
  columns: [
    { key: "dealDate",           label: "Дата сделки",           type: "date",   exportable: true },
    { key: "dealNumber",         label: "Номер",                 type: "string", exportable: true },
    { key: "departureName",      label: "Ст. отпр.",             type: "string", exportable: true },
    { key: "destinationName",    label: "Ст. назн.",             type: "string", exportable: true },
    { key: "buyerName",          label: "Покупатель",            type: "string", exportable: true },
    { key: "paymentDate",        label: "Дата оплаты",           type: "date",   exportable: true },
    { key: "pricePerTon",        label: "Цена/т (₽)",            type: "number", exportable: true },
    { key: "weightTon",          label: "Вес (т)",               type: "number", exportable: true },
    { key: "actualWeightTon",    label: "Вес фактический (т)",   type: "number", exportable: true },
    { key: "_purchaseAmount",    label: "Сумма покупки (₽)",     type: "number", exportable: true },
    { key: "tariffPricePerTon",  label: "Тариф (₽/т)",           type: "number", exportable: true },
    { key: "_deliveryCostTotal", label: "Доставка (₽)",          type: "number", exportable: true },
    { key: "_totalCost",         label: "Итого (₽)",             type: "number", exportable: true },
    { key: "_costPerTon",        label: "Цена итого (₽/т)",      type: "number", exportable: true },
    { key: "wagonDepartureDate", label: "Дата отправки вагонов", type: "date",   exportable: true },
    { key: "plannedDeliveryDate",label: "Дата план. доставки",   type: "date",   exportable: true },
    { key: "sellerName",         label: "Продавец",              type: "string", exportable: true },
    { key: "wagonNumbers",       label: "Вагоны",                type: "string", exportable: true },
    { key: "railwayInvoice",     label: "Ж/д накладная",         type: "string", exportable: true },
    { key: "_reserved",          label: "Резерв 5% (₽)",         type: "number", exportable: true },
    { key: "notes",              label: "Примечания",            type: "string", exportable: true },
  ],
  defaultColumns: ["dealDate","dealNumber","departureName","destinationName","buyerName","pricePerTon","weightTon","actualWeightTon","_purchaseAmount","_deliveryCostTotal","_totalCost","wagonDepartureDate","plannedDeliveryDate","sellerName"],
  relations: [],
};

export const warehousesExportConfig: ModuleExportConfig = {
  moduleName: "warehouses",
  tableName: "warehouses",
  displayName: "Склады",
  columns: [
    { key: "name",            label: "Название",              type: "string", exportable: true },
    { key: "currentBalance",  label: "Остаток керосина (кг)", type: "number", exportable: true },
    { key: "averageCost",     label: "Себест. керосина",      type: "number", exportable: true },
    { key: "pvkjBalance",     label: "Остаток ПВКЖ (кг)",     type: "number", exportable: true },
    { key: "pvkjAverageCost", label: "Себест. ПВКЖ",          type: "number", exportable: true },
    { key: "maxCapacity",     label: "Ёмкость (кг)",          type: "number", exportable: true },
    { key: "isActive",        label: "Активен",               type: "boolean",exportable: true },
  ],
  defaultColumns: ["name","currentBalance","averageCost","pvkjBalance","isActive"],
  relations: [],
};

export const transportationExportConfig: ModuleExportConfig = {
  moduleName: "transportation",
  tableName: "transportation",
  displayName: "Перевозки",
  columns: [
    { key: "dealDate",              label: "Дата",               type: "date",   exportable: true },
    { key: "buyer.name",            label: "Заказчик",           type: "string", exportable: true },
    { key: "supplier.name",         label: "Поставщик",          type: "string", exportable: true },
    { key: "carrier.name",          label: "Перевозчик",         type: "string", exportable: true },
    { key: "deliveryLocation.name", label: "Пункт доставки",     type: "string", exportable: true },
    { key: "basis",                 label: "Базис погрузки",     type: "string", exportable: true },
    { key: "customerBasis",         label: "Базис доставки",     type: "string", exportable: true },
    { key: "productType",           label: "Продукт",            type: "string", exportable: true },
    { key: "quantityKg",            label: "КГ",                 type: "number", exportable: true },
    { key: "salePrice",             label: "Цена услуги (₽/кг)", type: "number", exportable: true },
    { key: "saleAmount",            label: "Сумма услуги (₽)",   type: "number", exportable: true },
    { key: "deliveryCost",          label: "Доставка (₽)",       type: "number", exportable: true },
    { key: "profit",                label: "Прибыль (₽)",        type: "number", exportable: true },
    { key: "notes",                 label: "Примечание",         type: "string", exportable: true },
  ],
  defaultColumns: ["dealDate","buyer.name","carrier.name","deliveryLocation.name","quantityKg","salePrice","saleAmount","profit"],
  relations: ["buyer","supplier","carrier","deliveryLocation"],
};

export const refuelingAbroadExportConfig: ModuleExportConfig = {
  moduleName: "refueling-abroad",
  tableName: "refueling_abroad",
  displayName: "Заправка ВС зарубеж",
  columns: [
    { key: "refuelingDate",              label: "Дата",                  type: "date",   exportable: true },
    { key: "airport",                    label: "Аэропорт",              type: "string", exportable: true },
    { key: "aircraftNumber",             label: "Борт",                  type: "string", exportable: true },
    { key: "rtNumber",                   label: "Номер РТ",              type: "string", exportable: true },
    { key: "supplier.name",              label: "Поставщик",             type: "string", exportable: true },
    { key: "buyer.name",                 label: "Покупатель",            type: "string", exportable: true },
    { key: "basis.name",                 label: "Базис",                 type: "string", exportable: true },
    { key: "productType",                label: "Продукт",               type: "string", exportable: true },
    { key: "quantityLiters",             label: "Лит.",                  type: "number", exportable: true },
    { key: "quantityKg",                 label: "КГ",                    type: "number", exportable: true },
    { key: "purchasePriceUsd",           label: "Цена закупки (USD)",    type: "number", exportable: true },
    { key: "purchaseAmountUsd",          label: "Сумма закупки (USD)",   type: "number", exportable: true },
    { key: "purchaseExchangeRateValue",  label: "Курс закупки (₽)",      type: "number", exportable: true },
    { key: "purchaseAmountRub",          label: "Сумма закупки (₽)",     type: "number", exportable: true },
    { key: "salePriceUsd",               label: "Цена продажи (USD)",    type: "number", exportable: true },
    { key: "saleAmountUsd",              label: "Сумма продажи (USD)",   type: "number", exportable: true },
    { key: "saleExchangeRateValue",      label: "Курс продажи (₽)",      type: "number", exportable: true },
    { key: "saleAmountRub",              label: "Сумма продажи (₽)",     type: "number", exportable: true },
    { key: "_totalIntermediaryUsd",      label: "Посредники (USD)",      type: "number", exportable: true },
    { key: "_totalBankCommissionUsd",    label: "Банк. комиссии (USD)",  type: "number", exportable: true },
    { key: "_totalCommissionUsd",        label: "Сумма комиссий (USD)",  type: "number", exportable: true },
    { key: "profitUsd",                  label: "Прибыль (USD)",         type: "number", exportable: true },
    { key: "profitRub",                  label: "Прибыль (₽)",           type: "number", exportable: true },
  ],
  defaultColumns: ["refuelingDate","airport","aircraftNumber","supplier.name","buyer.name","quantityKg","purchasePriceUsd","purchaseAmountUsd","salePriceUsd","saleAmountUsd","profitUsd"],
  relations: ["supplier","buyer","basis"],
};

export const equipmentMovementExportConfig: ModuleExportConfig = {
  moduleName: "equipment-movement",
  tableName: "equipment_movement",
  displayName: "Перемещения ОП",
  columns: [
    { key: "movementDate",      label: "Дата",           type: "date",   exportable: true },
    { key: "movementType",      label: "Тип",            type: "string", exportable: true },
    { key: "productType",       label: "Продукт",        type: "string", exportable: true },
    { key: "fromWarehouseName", label: "Склад (откуда)", type: "string", exportable: true },
    { key: "fromEquipmentName", label: "ОП (откуда)",    type: "string", exportable: true },
    { key: "toWarehouseName",   label: "Склад (куда)",   type: "string", exportable: true },
    { key: "toEquipmentName",   label: "ОП (куда)",      type: "string", exportable: true },
    { key: "quantityKg",        label: "КГ",             type: "number", exportable: true },
    { key: "quantityLiters",    label: "Лит.",           type: "number", exportable: true },
    { key: "density",           label: "Плотность",      type: "number", exportable: true },
    { key: "costPerKg",         label: "Себест. (₽/кг)", type: "number", exportable: true },
    { key: "totalCost",         label: "Сумма (₽)",      type: "number", exportable: true },
    { key: "notes",             label: "Примечания",     type: "string", exportable: true },
  ],
  defaultColumns: ["movementDate","movementType","productType","fromWarehouseName","toWarehouseName","fromEquipmentName","toEquipmentName","quantityKg","costPerKg","totalCost"],
  relations: [],
};

export const deliveryCostExportConfig: ModuleExportConfig = {
  moduleName: "delivery-cost",
  tableName: "delivery_costs",
  displayName: "Тарифы доставки",
  columns: [
    { key: "carrierName",  label: "Перевозчик",      type: "string", exportable: true },
    { key: "fromLocation", label: "Откуда",          type: "string", exportable: true },
    { key: "toLocation",   label: "Куда",            type: "string", exportable: true },
    { key: "costPerKg",    label: "За кг (₽)",       type: "number", exportable: true },
    { key: "distanceKm",   label: "Расстояние (км)", type: "number", exportable: true },
    { key: "isActive",     label: "Активен",         type: "boolean",exportable: true },
  ],
  defaultColumns: ["carrierName","fromLocation","toLocation","costPerKg","isActive"],
  relations: [],
};

export const railwayTariffsExportConfig: ModuleExportConfig = {
  moduleName: "railway-tariffs",
  tableName: "railway_tariffs",
  displayName: "Тарифы ЖД доставки",
  columns: [
    { key: "fromStation.name", label: "Ст. отправления", type: "string", exportable: true },
    { key: "toStation.name",   label: "Ст. назначения",  type: "string", exportable: true },
    { key: "pricePerTon",      label: "Тариф (₽/т)",     type: "number", exportable: true },
  ],
  defaultColumns: ["fromStation.name","toStation.name","pricePerTon"],
  relations: [],
};

export const exportConfigRegistry: Record<string, ModuleExportConfig> = {
  opt:                  optExportConfig,
  refueling:            refuelingExportConfig,
  movement:             movementExportConfig,
  "exchange-deals":     exchangeDealsExportConfig,
  warehouses:           warehousesExportConfig,
  transportation:       transportationExportConfig,
  "refueling-abroad":   refuelingAbroadExportConfig,
  "equipment-movement": equipmentMovementExportConfig,
  "delivery-cost":      deliveryCostExportConfig,
  "railway-tariffs":    railwayTariffsExportConfig,
};
